### ISSUE TITLE
The checklist challenges in Mint Royale Nations.

### ISSUE THREAD

**Issue by sinaizd** [sinaizd/miniroyale#3]
- [ ] Check all screens for compliance with the design
- [ ] Check if it is screens correctly adapted for mobile browsers
- [ ] Check whether the buttons work correctly on all screens when clicked
- [ ] Check whether the progress is displayed correctly in the progress bar when completing a mission 
- [ ] Check that the rewards are not available if the mission is not completed
- [ ] Check that rewards are available if missions are completed
- [ ] Check claim reward
- [ ] Check the end time of the challenge
